FROM ubuntu

RUN apt update && apt install git -y \
	&& apt install build-essential -y \
	&& apt install bash -y \
	&& apt-get install gcc-multilib -y

WORKDIR /home/app/

RUN git clone https://github.com/VladimirNikel/SP_laba7.git \
	&& cd SP_laba7/ \
	&& g++ ./data/client/client.cpp -o client_data \
	&& g++ ./flow/client/client.cpp -o client_flow \
	&& chmod ugo+xs client_data && chmod ugo+xs client_flow

WORKDIR /home/app/SP_laba7/

EXPOSE 8080
